import { Department, Officer, UserProfile } from '../types';
import { FirestoreDepartment, FirestoreOfficer, FirestoreUser } from '../types/firestore';

export const MAIN_ADMIN_USER: UserProfile = {
  id: 'admin_sriram_venkatesan',
  name: 'Sriram Venkatesan',
  email: 'sriramv2116.sse@saveetha.com',
  phone: '9840261962',
  role: 'ADMIN',
  departmentId: 'ALL',
  departmentName: 'ALL DEPARTMENTS',
  badgeNumber: 'IAS-SEVA-CHIEF-001',
  area: 'Greater Chennai Metropolitan Authority',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  preferredLanguage: 'en'
};

export const SEVA_18_DEPARTMENTS: Department[] = [
  {
    id: 'dept-municipal',
    code: 'MUNICIPAL',
    name: 'Municipal Corporation',
    tamilName: 'மாநகராட்சி நிர்வாகம்',
    iconName: 'Building2',
    defaultSlaHours: 48,
    officerCount: 14,
    activeCases: 18,
    resolvedCases: 142,
    slaComplianceRate: 88,
    performanceScore: 91,
    contactEmail: 'municipal.admin@seva-demo.gov',
    contactHelpline: '1913'
  },
  {
    id: 'dept-water',
    code: 'WATER',
    name: 'Water Supply Department',
    tamilName: 'குடிநீர் வழங்கல் வாரியம்',
    iconName: 'Droplets',
    defaultSlaHours: 24,
    officerCount: 12,
    activeCases: 14,
    resolvedCases: 128,
    slaComplianceRate: 84,
    performanceScore: 88,
    contactEmail: 'water.admin@seva-demo.gov',
    contactHelpline: '1916'
  },
  {
    id: 'dept-electricity',
    code: 'ELECTRICITY',
    name: 'Electricity Department',
    tamilName: 'மின்சார வாரியம்',
    iconName: 'Zap',
    defaultSlaHours: 8,
    officerCount: 16,
    activeCases: 9,
    resolvedCases: 194,
    slaComplianceRate: 94,
    performanceScore: 96,
    contactEmail: 'electricity.admin@seva-demo.gov',
    contactHelpline: '1912'
  },
  {
    id: 'dept-roads',
    code: 'ROADS',
    name: 'Roads & Highways Department',
    tamilName: 'நெடுஞ்சாலைகள் & சாலைத்துறை',
    iconName: 'Truck',
    defaultSlaHours: 48,
    officerCount: 18,
    activeCases: 23,
    resolvedCases: 165,
    slaComplianceRate: 79,
    performanceScore: 82,
    contactEmail: 'roads.admin@seva-demo.gov',
    contactHelpline: '1800-425-4321'
  },
  {
    id: 'dept-sanitation',
    code: 'SANITATION',
    name: 'Sanitation & Solid Waste Department',
    tamilName: 'திடக்கழிவு மேலாண்மைத் துறை',
    iconName: 'Trash2',
    defaultSlaHours: 24,
    officerCount: 22,
    activeCases: 16,
    resolvedCases: 230,
    slaComplianceRate: 92,
    performanceScore: 94,
    contactEmail: 'sanitation.admin@seva-demo.gov',
    contactHelpline: '1913'
  },
  {
    id: 'dept-lighting',
    code: 'LIGHTING',
    name: 'Street Lighting Department',
    tamilName: 'தெருவிளக்குகள் பராமரிப்பு',
    iconName: 'SunMedium',
    defaultSlaHours: 24,
    officerCount: 8,
    activeCases: 7,
    resolvedCases: 98,
    slaComplianceRate: 91,
    performanceScore: 90,
    contactEmail: 'lighting.admin@seva-demo.gov',
    contactHelpline: '1913'
  },
  {
    id: 'dept-drainage',
    code: 'DRAINAGE',
    name: 'Drainage & Stormwater Department',
    tamilName: 'மழைநீர் வடிகால் & கழிவுநீரகத்துறை',
    iconName: 'Waves',
    defaultSlaHours: 24,
    officerCount: 10,
    activeCases: 12,
    resolvedCases: 110,
    slaComplianceRate: 85,
    performanceScore: 86,
    contactEmail: 'drainage.admin@seva-demo.gov',
    contactHelpline: '1916'
  },
  {
    id: 'dept-transport',
    code: 'TRANSPORT',
    name: 'Public Transport Department',
    tamilName: 'போக்குவரத்துக் கழகம்',
    iconName: 'Bus',
    defaultSlaHours: 36,
    officerCount: 10,
    activeCases: 5,
    resolvedCases: 72,
    slaComplianceRate: 89,
    performanceScore: 88,
    contactEmail: 'transport.admin@seva-demo.gov',
    contactHelpline: '1800-599-1500'
  },
  {
    id: 'dept-traffic',
    code: 'TRAFFIC',
    name: 'Traffic Management Department',
    tamilName: 'போக்குவரத்து காவல்துறை',
    iconName: 'Compass',
    defaultSlaHours: 12,
    officerCount: 15,
    activeCases: 8,
    resolvedCases: 140,
    slaComplianceRate: 93,
    performanceScore: 95,
    contactEmail: 'traffic.admin@seva-demo.gov',
    contactHelpline: '103'
  },
  {
    id: 'dept-healthcare',
    code: 'HEALTHCARE',
    name: 'Healthcare Department',
    tamilName: 'மக்கள் நல்வாழ்வுத்துறை',
    iconName: 'HeartPulse',
    defaultSlaHours: 12,
    officerCount: 14,
    activeCases: 4,
    resolvedCases: 86,
    slaComplianceRate: 96,
    performanceScore: 97,
    contactEmail: 'healthcare.admin@seva-demo.gov',
    contactHelpline: '104'
  },
  {
    id: 'dept-publichealth',
    code: 'PUBLICHEALTH',
    name: 'Public Health Department',
    tamilName: 'பொது சுகாதாரத்துறை',
    iconName: 'ShieldAlert',
    defaultSlaHours: 24,
    officerCount: 11,
    activeCases: 6,
    resolvedCases: 92,
    slaComplianceRate: 90,
    performanceScore: 91,
    contactEmail: 'publichealth.admin@seva-demo.gov',
    contactHelpline: '104'
  },
  {
    id: 'dept-police',
    code: 'POLICE',
    name: 'Police & Public Safety Department',
    tamilName: 'காவல்துறை & பொதுப்பாதுகாப்பு',
    iconName: 'Shield',
    defaultSlaHours: 8,
    officerCount: 20,
    activeCases: 11,
    resolvedCases: 210,
    slaComplianceRate: 95,
    performanceScore: 97,
    contactEmail: 'police.admin@seva-demo.gov',
    contactHelpline: '100'
  },
  {
    id: 'dept-fire',
    code: 'FIRE',
    name: 'Fire & Emergency Services',
    tamilName: 'தீயணைப்பு & மீட்புப்பணிகள்',
    iconName: 'Flame',
    defaultSlaHours: 4,
    officerCount: 16,
    activeCases: 2,
    resolvedCases: 115,
    slaComplianceRate: 98,
    performanceScore: 99,
    contactEmail: 'fire.admin@seva-demo.gov',
    contactHelpline: '101'
  },
  {
    id: 'dept-disaster',
    code: 'DISASTER',
    name: 'Disaster Management Department',
    tamilName: 'பேரிடர் மேலாண்மை ஆணையம்',
    iconName: 'AlertTriangle',
    defaultSlaHours: 6,
    officerCount: 14,
    activeCases: 3,
    resolvedCases: 78,
    slaComplianceRate: 96,
    performanceScore: 98,
    contactEmail: 'disaster.admin@seva-demo.gov',
    contactHelpline: '1070'
  },
  {
    id: 'dept-parks',
    code: 'PARKS',
    name: 'Parks & Public Spaces Department',
    tamilName: 'பூங்காக்கள் & பொது இடங்கள்',
    iconName: 'Trees',
    defaultSlaHours: 72,
    officerCount: 8,
    activeCases: 5,
    resolvedCases: 64,
    slaComplianceRate: 86,
    performanceScore: 87,
    contactEmail: 'parks.admin@seva-demo.gov',
    contactHelpline: '1913'
  },
  {
    id: 'dept-animal',
    code: 'ANIMAL',
    name: 'Animal Control Department',
    tamilName: 'விலங்குகள் கட்டுப்பாடு & பராமரிப்பு',
    iconName: 'Cat',
    defaultSlaHours: 24,
    officerCount: 7,
    activeCases: 6,
    resolvedCases: 52,
    slaComplianceRate: 84,
    performanceScore: 85,
    contactEmail: 'animal.admin@seva-demo.gov',
    contactHelpline: '1913'
  },
  {
    id: 'dept-environment',
    code: 'ENVIRONMENT',
    name: 'Environmental Services Department',
    tamilName: 'சுற்றுச்சூழல் பாதுகாப்புத்துறை',
    iconName: 'Leaf',
    defaultSlaHours: 48,
    officerCount: 9,
    activeCases: 7,
    resolvedCases: 61,
    slaComplianceRate: 87,
    performanceScore: 89,
    contactEmail: 'environment.admin@seva-demo.gov',
    contactHelpline: '1800-425-3333'
  },
  {
    id: 'dept-building',
    code: 'BUILDING',
    name: 'Building & Infrastructure Department',
    tamilName: 'கட்டிட வரைமுறை & உள்கட்டமைப்பு',
    iconName: 'HardHat',
    defaultSlaHours: 72,
    officerCount: 10,
    activeCases: 8,
    resolvedCases: 59,
    slaComplianceRate: 82,
    performanceScore: 84,
    contactEmail: 'building.admin@seva-demo.gov',
    contactHelpline: '1913'
  }
];

export const DEPARTMENT_ADMIN_USERS: UserProfile[] = [
  {
    id: 'adm_municipal',
    name: 'Ananya Rao',
    email: 'municipal.admin@seva-demo.gov',
    phone: '9840100001',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-municipal',
    departmentName: 'Municipal Corporation',
    badgeNumber: 'MC-ADM-01',
    area: 'Ward 168',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'
  },
  {
    id: 'adm_water',
    name: 'Vikram Iyer',
    email: 'water.admin@seva-demo.gov',
    phone: '9840100002',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-water',
    departmentName: 'Water Supply Department',
    badgeNumber: 'WTR-ADM-02',
    area: 'Zone 14',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },
  {
    id: 'adm_electricity',
    name: 'Priya Menon',
    email: 'electricity.admin@seva-demo.gov',
    phone: '9840100003',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-electricity',
    departmentName: 'Electricity Department',
    badgeNumber: 'ELEC-ADM-03',
    area: 'South Distribution',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'
  },
  {
    id: 'adm_roads',
    name: 'Arjun Nair',
    email: 'roads.admin@seva-demo.gov',
    phone: '9840100004',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-roads',
    departmentName: 'Roads & Highways Department',
    badgeNumber: 'RD-ADM-04',
    area: 'Central Zone',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'adm_sanitation',
    name: 'Meera Shah',
    email: 'sanitation.admin@seva-demo.gov',
    phone: '9840100005',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-sanitation',
    departmentName: 'Sanitation & Solid Waste Department',
    badgeNumber: 'SWM-ADM-05',
    area: 'Ward 160-175',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150'
  },
  {
    id: 'adm_lighting',
    name: 'Karan Mehta',
    email: 'lighting.admin@seva-demo.gov',
    phone: '9840100006',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-lighting',
    departmentName: 'Street Lighting Department',
    badgeNumber: 'LT-ADM-06',
    area: 'South Suburbs',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'
  },
  {
    id: 'adm_drainage',
    name: 'Neha Kapoor',
    email: 'drainage.admin@seva-demo.gov',
    phone: '9840100007',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-drainage',
    departmentName: 'Drainage & Stormwater Department',
    badgeNumber: 'DRN-ADM-07',
    area: 'Velachery-Madipakkam Basin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150'
  },
  {
    id: 'adm_transport',
    name: 'Rohit Verma',
    email: 'transport.admin@seva-demo.gov',
    phone: '9840100008',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-transport',
    departmentName: 'Public Transport Department',
    badgeNumber: 'TRN-ADM-08',
    area: 'Metropolitan Corridors',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'
  },
  {
    id: 'adm_traffic',
    name: 'Divya Krishnan',
    email: 'traffic.admin@seva-demo.gov',
    phone: '9840100009',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-traffic',
    departmentName: 'Traffic Management Department',
    badgeNumber: 'TRF-ADM-09',
    area: 'South Traffic Sector',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150'
  },
  {
    id: 'adm_healthcare',
    name: 'Rahul Menon',
    email: 'healthcare.admin@seva-demo.gov',
    phone: '9840100010',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-healthcare',
    departmentName: 'Healthcare Department',
    badgeNumber: 'HLT-ADM-10',
    area: 'Primary Health Centers',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150'
  },
  {
    id: 'adm_publichealth',
    name: 'Kavya Rao',
    email: 'publichealth.admin@seva-demo.gov',
    phone: '9840100011',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-publichealth',
    departmentName: 'Public Health Department',
    badgeNumber: 'PBH-ADM-11',
    area: 'Epidemic & Vector Surveillance',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150'
  },
  {
    id: 'adm_police',
    name: 'Aditya Sharma',
    email: 'police.admin@seva-demo.gov',
    phone: '9840100012',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-police',
    departmentName: 'Police & Public Safety Department',
    badgeNumber: 'POL-ADM-12',
    area: 'Law & Order Division',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'
  },
  {
    id: 'adm_fire',
    name: 'Sanjay Patel',
    email: 'fire.admin@seva-demo.gov',
    phone: '9840100013',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-fire',
    departmentName: 'Fire & Emergency Services',
    badgeNumber: 'FIR-ADM-13',
    area: 'Fire Command Station 4',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'adm_disaster',
    name: 'Nisha Singh',
    email: 'disaster.admin@seva-demo.gov',
    phone: '9840100014',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-disaster',
    departmentName: 'Disaster Management Department',
    badgeNumber: 'DIS-ADM-14',
    area: 'State Emergency Operations',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'
  },
  {
    id: 'adm_parks',
    name: 'Rohan Das',
    email: 'parks.admin@seva-demo.gov',
    phone: '9840100015',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-parks',
    departmentName: 'Parks & Public Spaces Department',
    badgeNumber: 'PRK-ADM-15',
    area: 'Urban Green Corridors',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150'
  },
  {
    id: 'adm_animal',
    name: 'Ishita Rao',
    email: 'animal.admin@seva-demo.gov',
    phone: '9840100016',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-animal',
    departmentName: 'Animal Control Department',
    badgeNumber: 'ANM-ADM-16',
    area: 'Veterinary Control Zone',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150'
  },
  {
    id: 'adm_environment',
    name: 'Varun Kumar',
    email: 'environment.admin@seva-demo.gov',
    phone: '9840100017',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-environment',
    departmentName: 'Environmental Services Department',
    badgeNumber: 'ENV-ADM-17',
    area: 'Pollution Control & Air Quality',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150'
  },
  {
    id: 'adm_building',
    name: 'Sneha Iyer',
    email: 'building.admin@seva-demo.gov',
    phone: '9840100018',
    role: 'DEPARTMENT_ADMIN',
    departmentId: 'dept-building',
    departmentName: 'Building & Infrastructure Department',
    badgeNumber: 'BLD-ADM-18',
    area: 'Town Planning & Structural Safety',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'
  }
];

export const DEPARTMENT_OFFICERS: Officer[] = [
  // Municipal Corporation Officers
  {
    id: 'off_mc_1',
    name: 'Karthik Raj',
    badge: 'MC-ENG-082',
    departmentId: 'dept-municipal',
    departmentName: 'Municipal Corporation',
    role: 'OFFICER',
    phone: '9840200001',
    email: 'karthik.municipal@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 48,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },
  {
    id: 'off_mc_2',
    name: 'Harish Kumar',
    badge: 'MC-ENG-094',
    departmentId: 'dept-municipal',
    departmentName: 'Municipal Corporation',
    role: 'OFFICER',
    phone: '9840200002',
    email: 'harish.municipal@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 52,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },

  // Water Supply Officers
  {
    id: 'off_wtr_1',
    name: 'Manoj Kumar',
    badge: 'WTR-SUP-041',
    departmentId: 'dept-water',
    departmentName: 'Water Supply Department',
    role: 'OFFICER',
    phone: '9840200003',
    email: 'manoj.water@seva-demo.gov',
    activeAssignments: 4,
    resolvedCases: 63,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'
  },
  {
    id: 'off_wtr_2',
    name: 'Deepa Raj',
    badge: 'WTR-SUP-055',
    departmentId: 'dept-water',
    departmentName: 'Water Supply Department',
    role: 'OFFICER',
    phone: '9840200004',
    email: 'deepa.water@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 41,
    rating: 4.6,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'
  },

  // Electricity Officers
  {
    id: 'off_elec_1',
    name: 'Suresh Babu',
    badge: 'ELEC-AE-102',
    departmentId: 'dept-electricity',
    departmentName: 'Electricity Department',
    role: 'OFFICER',
    phone: '9840200005',
    email: 'suresh.elec@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 89,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'
  },
  {
    id: 'off_elec_2',
    name: 'Gowri Shankar',
    badge: 'ELEC-AE-118',
    departmentId: 'dept-electricity',
    departmentName: 'Electricity Department',
    role: 'OFFICER',
    phone: '9840200006',
    email: 'gowri.elec@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 76,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'
  },

  // Roads & Highways Officers
  {
    id: 'off_rd_1',
    name: 'Rajesh Kannan',
    badge: 'RD-ENG-201',
    departmentId: 'dept-roads',
    departmentName: 'Roads & Highways Department',
    role: 'OFFICER',
    phone: '9840200007',
    email: 'rajesh.roads@seva-demo.gov',
    activeAssignments: 5,
    resolvedCases: 71,
    rating: 4.6,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'off_rd_2',
    name: 'Praveen Chander',
    badge: 'RD-ENG-214',
    departmentId: 'dept-roads',
    departmentName: 'Roads & Highways Department',
    role: 'OFFICER',
    phone: '9840200008',
    email: 'praveen.roads@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 58,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150'
  },

  // Sanitation Officers
  {
    id: 'off_swm_1',
    name: 'Vasanth Kumar',
    badge: 'SWM-INSP-012',
    departmentId: 'dept-sanitation',
    departmentName: 'Sanitation & Solid Waste Department',
    role: 'OFFICER',
    phone: '9840200009',
    email: 'vasanth.sanitation@seva-demo.gov',
    activeAssignments: 4,
    resolvedCases: 110,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150'
  },
  {
    id: 'off_swm_2',
    name: 'Lakshmi Narayanan',
    badge: 'SWM-INSP-019',
    departmentId: 'dept-sanitation',
    departmentName: 'Sanitation & Solid Waste Department',
    role: 'OFFICER',
    phone: '9840200010',
    email: 'lakshmi.sanitation@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 95,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },

  // Street Lighting Officers
  {
    id: 'off_lt_1',
    name: 'Dinesh Balan',
    badge: 'LT-TECH-008',
    departmentId: 'dept-lighting',
    departmentName: 'Street Lighting Department',
    role: 'OFFICER',
    phone: '9840200011',
    email: 'dinesh.lighting@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 44,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'
  },
  {
    id: 'off_lt_2',
    name: 'Saravanan M',
    badge: 'LT-TECH-014',
    departmentId: 'dept-lighting',
    departmentName: 'Street Lighting Department',
    role: 'OFFICER',
    phone: '9840200012',
    email: 'saravanan.lighting@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 51,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'
  },

  // Drainage Officers
  {
    id: 'off_drn_1',
    name: 'Balaji Natarajan',
    badge: 'DRN-ENG-033',
    departmentId: 'dept-drainage',
    departmentName: 'Drainage & Stormwater Department',
    role: 'OFFICER',
    phone: '9840200013',
    email: 'balaji.drainage@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 62,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'
  },
  {
    id: 'off_drn_2',
    name: 'Gayathri Sundar',
    badge: 'DRN-ENG-047',
    departmentId: 'dept-drainage',
    departmentName: 'Drainage & Stormwater Department',
    role: 'OFFICER',
    phone: '9840200014',
    email: 'gayathri.drainage@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 49,
    rating: 4.6,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150'
  },

  // Transport Officers
  {
    id: 'off_trn_1',
    name: 'Kishore Venkat',
    badge: 'TRN-OPS-022',
    departmentId: 'dept-transport',
    departmentName: 'Public Transport Department',
    role: 'OFFICER',
    phone: '9840200015',
    email: 'kishore.transport@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 37,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'off_trn_2',
    name: 'Madhavan S',
    badge: 'TRN-OPS-031',
    departmentId: 'dept-transport',
    departmentName: 'Public Transport Department',
    role: 'OFFICER',
    phone: '9840200016',
    email: 'madhavan.transport@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 42,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150'
  },

  // Traffic Officers
  {
    id: 'off_trf_1',
    name: 'Inspector Anand',
    badge: 'TRF-INS-105',
    departmentId: 'dept-traffic',
    departmentName: 'Traffic Management Department',
    role: 'OFFICER',
    phone: '9840200017',
    email: 'anand.traffic@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 88,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },
  {
    id: 'off_trf_2',
    name: 'SI Vijayaraghavan',
    badge: 'TRF-SI-112',
    departmentId: 'dept-traffic',
    departmentName: 'Traffic Management Department',
    role: 'OFFICER',
    phone: '9840200018',
    email: 'vijay.traffic@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 74,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'
  },

  // Healthcare Officers
  {
    id: 'off_hlt_1',
    name: 'Dr. Sangeetha S',
    badge: 'HLT-MO-014',
    departmentId: 'dept-healthcare',
    departmentName: 'Healthcare Department',
    role: 'OFFICER',
    phone: '9840200019',
    email: 'sangeetha.health@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 56,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'
  },
  {
    id: 'off_hlt_2',
    name: 'Dr. Vignesh K',
    badge: 'HLT-MO-022',
    departmentId: 'dept-healthcare',
    departmentName: 'Healthcare Department',
    role: 'OFFICER',
    phone: '9840200020',
    email: 'vignesh.health@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 48,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150'
  },

  // Public Health Officers
  {
    id: 'off_pbh_1',
    name: 'Health Inspector Ramesh',
    badge: 'PBH-HI-009',
    departmentId: 'dept-publichealth',
    departmentName: 'Public Health Department',
    role: 'OFFICER',
    phone: '9840200021',
    email: 'ramesh.pubhealth@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 59,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'
  },
  {
    id: 'off_pbh_2',
    name: 'Sanitary Officer Shanti',
    badge: 'PBH-SO-018',
    departmentId: 'dept-publichealth',
    departmentName: 'Public Health Department',
    role: 'OFFICER',
    phone: '9840200022',
    email: 'shanti.pubhealth@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 45,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'
  },

  // Police & Public Safety Officers
  {
    id: 'off_pol_1',
    name: 'SI Karthikeyan',
    badge: 'POL-SI-402',
    departmentId: 'dept-police',
    departmentName: 'Police & Public Safety Department',
    role: 'OFFICER',
    phone: '9840200023',
    email: 'karthik.police@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 118,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'
  },
  {
    id: 'off_pol_2',
    name: 'Inspector Meenakshi',
    badge: 'POL-INS-390',
    departmentId: 'dept-police',
    departmentName: 'Police & Public Safety Department',
    role: 'OFFICER',
    phone: '9840200024',
    email: 'meenakshi.police@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 125,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150'
  },

  // Fire & Emergency Officers
  {
    id: 'off_fir_1',
    name: 'Station Officer Raghavan',
    badge: 'FIR-SO-05',
    departmentId: 'dept-fire',
    departmentName: 'Fire & Emergency Services',
    role: 'OFFICER',
    phone: '9840200025',
    email: 'raghavan.fire@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 67,
    rating: 5.0,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },
  {
    id: 'off_fir_2',
    name: 'Lead Firefighter Mani',
    badge: 'FIR-LF-18',
    departmentId: 'dept-fire',
    departmentName: 'Fire & Emergency Services',
    role: 'OFFICER',
    phone: '9840200026',
    email: 'mani.fire@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 54,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'
  },

  // Disaster Management Officers
  {
    id: 'off_dis_1',
    name: 'Rescue Lead Ashwin',
    badge: 'DIS-RL-01',
    departmentId: 'dept-disaster',
    departmentName: 'Disaster Management Department',
    role: 'OFFICER',
    phone: '9840200027',
    email: 'ashwin.disaster@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 46,
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'off_dis_2',
    name: 'Emergency Coordinator Tara',
    badge: 'DIS-EC-08',
    departmentId: 'dept-disaster',
    departmentName: 'Disaster Management Department',
    role: 'OFFICER',
    phone: '9840200028',
    email: 'tara.disaster@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 38,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150'
  },

  // Parks & Public Spaces Officers
  {
    id: 'off_prk_1',
    name: 'Horticulturist Devan',
    badge: 'PRK-HC-04',
    departmentId: 'dept-parks',
    departmentName: 'Parks & Public Spaces Department',
    role: 'OFFICER',
    phone: '9840200029',
    email: 'devan.parks@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 33,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'
  },
  {
    id: 'off_prk_2',
    name: 'Facility Supervisor Malathi',
    badge: 'PRK-FS-11',
    departmentId: 'dept-parks',
    departmentName: 'Parks & Public Spaces Department',
    role: 'OFFICER',
    phone: '9840200030',
    email: 'malathi.parks@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 39,
    rating: 4.6,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'
  },

  // Animal Control Officers
  {
    id: 'off_anm_1',
    name: 'Vet Officer Dr. Pradeep',
    badge: 'ANM-VO-03',
    departmentId: 'dept-animal',
    departmentName: 'Animal Control Department',
    role: 'OFFICER',
    phone: '9840200031',
    email: 'pradeep.animal@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 35,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150'
  },
  {
    id: 'off_anm_2',
    name: 'Rescue Worker Jayaraj',
    badge: 'ANM-RW-09',
    departmentId: 'dept-animal',
    departmentName: 'Animal Control Department',
    role: 'OFFICER',
    phone: '9840200032',
    email: 'jayaraj.animal@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 29,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'
  },

  // Environment Officers
  {
    id: 'off_env_1',
    name: 'Pollution Officer Gowtham',
    badge: 'ENV-PO-07',
    departmentId: 'dept-environment',
    departmentName: 'Environmental Services Department',
    role: 'OFFICER',
    phone: '9840200033',
    email: 'gowtham.env@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 36,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
  },
  {
    id: 'off_env_2',
    name: 'Inspector Geetha',
    badge: 'ENV-INS-15',
    departmentId: 'dept-environment',
    departmentName: 'Environmental Services Department',
    role: 'OFFICER',
    phone: '9840200034',
    email: 'geetha.env@seva-demo.gov',
    activeAssignments: 1,
    resolvedCases: 31,
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150'
  },

  // Building & Infrastructure Officers
  {
    id: 'off_bld_1',
    name: 'Structural Engineer Senthil',
    badge: 'BLD-SE-02',
    departmentId: 'dept-building',
    departmentName: 'Building & Infrastructure Department',
    role: 'OFFICER',
    phone: '9840200035',
    email: 'senthil.building@seva-demo.gov',
    activeAssignments: 3,
    resolvedCases: 34,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'
  },
  {
    id: 'off_bld_2',
    name: 'Town Planner Radhika',
    badge: 'BLD-TP-06',
    departmentId: 'dept-building',
    departmentName: 'Building & Infrastructure Department',
    role: 'OFFICER',
    phone: '9840200036',
    email: 'radhika.building@seva-demo.gov',
    activeAssignments: 2,
    resolvedCases: 30,
    rating: 4.7,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150'
  }
];

export const DEMO_CITIZEN_USERS: UserProfile[] = [
  {
    id: 'cit_ananya_sharma',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@example.com',
    phone: '+91 98401 88291',
    role: 'CITIZEN',
    area: 'Madipakkam, Ward 168',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    preferredLanguage: 'ta'
  },
  {
    id: 'cit_priya_sundaram',
    name: 'Priya Sundaram',
    email: 'priya.sundaram@example.com',
    phone: '+91 94440 12894',
    role: 'CITIZEN',
    area: 'Velachery Bypass Road',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    preferredLanguage: 'en'
  },
  {
    id: 'cit_r_kumar',
    name: 'R. Kumar',
    email: 'r.kumar@example.com',
    phone: '+91 97910 44820',
    role: 'CITIZEN',
    area: 'Nanganallur 4th Main Road',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    preferredLanguage: 'ta'
  }
];
